### ISSUE TITLE
Use OTEL_EXPORTER_OTLP_ENDPOINT

### ISSUE THREAD

**Issue by paf31** [hasura/ndc-sdk-python#1]
`OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` which should be `OTEL_EXPORTER_OTLP_ENDPOINT` (since it's used for both metrics and traces)

**Comment by TristenHarr** [comment]
This has been fixed. https://github.com/hasura/ndc-sdk-python/commit/654886ed302b6f6bfd7f0b203c680f4f7f853695
