### ISSUE TITLE
Generated type names should not include nullability

### ISSUE THREAD

**Issue by abhinav-hasura** [hasura/ndc-sdk-python#3]
If a function is defined like this:

@connector.register_query
def foo() -> Foo | null

this produces a type in the NDC schema called "foo_nullable", and marks the return type of the function as:
```
nullable:
  named: foo_nullable
```

Instead it should produce a type called "foo" and mark the return type as:
```
nullable:
  named: foo
```

**Comment by TristenHarr** [comment]
This has been fixed. https://github.com/hasura/ndc-sdk-python/commit/7b5090b4c32086bd158ca2f219e2454751b51406
