### ISSUE TITLE
Selection set on nullable types error out

### ISSUE THREAD

**Issue by abhinav-hasura** [hasura/ndc-sdk-python#4]
If I have a function like this:

```
class Foo(BaseModel):
  bar: str

@connector.register_query
def foo() -> Foo | null:
  return None
```

The following graphql query will fail:

```
query {
  foo {
    bar
  }
}
```

because the python sdk tries to read the property "bar" of the return value of "foo". Instead it should check if the return value is None, and if so just return null in the connector response.

**Comment by TristenHarr** [comment]
Fixed: https://github.com/hasura/ndc-sdk-python/commit/7b5090b4c32086bd158ca2f219e2454751b51406
